Part1
cudabanger/PFMCPP_Project7 pull request #1
Opened 2021-08-25 04:00 UTC by cudabanger

2021-08-25 04:37 UTC, matkatmusic requested changes

2021-08-25 04:37 UTC, matkatmusic commented on AttackItem.cpp
> +#include "Utility.h"
Don't include what you don't use.
- [ ] revise

2021-08-25 04:37 UTC, matkatmusic commented on Character.cpp
> +        *initialAttackDamage = attackDamage;
You are doing the same thing 3 times over with pairs of variables.
Write a free function, pass in your pairs of variables, and D.R.Y.
- [ ] revise

2021-08-25 04:37 UTC, matkatmusic commented on DefensiveItem.cpp
Don't include what you don't use.
- [ ] revise

2021-08-25 04:37 UTC, matkatmusic commented on DragonSlayer.h
> +    std::vector<std::unique_ptr<Item>> attackItems;
DragonSlayer gets ONE attack item, not a vector of them.
Also, this should be private.
- [ ] revise

2021-08-25 04:37 UTC, matkatmusic commented on Item.cpp
> +}
This function was pure virtual for a reason.
Do not provide an implementation
- [ ] remove this implementation.  Derived classes need to implement it.

2021-08-25 04:37 UTC, matkatmusic commented on Utility.cpp
> +
Remove this function
- [ ] revise

2021-08-25 04:37 UTC, matkatmusic commented on Utility.h
> +#define RANDOM_NUMBER rand() % 10 + 1
Don't make a macro for this.
Make a free function
- [ ] revise

2021-08-25 04:37 UTC, matkatmusic commented on main.cpp
> +    DragonSlayer dragonSlayer { "Virgil the Dragon Slayer", 8, 5, 4 };
Don't revise `main()`
- [ ] revert

2021-08-25 17:08 UTC, cudabanger commented on DragonSlayer.h
> +    std::vector<std::unique_ptr<Item>> attackItems;
I thought this implementation was functionally equivalent, consistent with design for HelpfulItem and DefensiveItem and would flexibly scale should the specification change to allow more then ONE.  With this new change, if DragonSlayer should ever get more then one AttackItem, a code change is required.  That was the motivation however, satisfying the Project Manager is a necessary function and that is exercised here.  You could argue that a vector was needless complexity if DragonSlayer would NEVER get more then one, and you would be right.

2021-08-26 03:18 UTC, matkatmusic requested changes
One change needed.

2021-08-26 03:18 UTC, matkatmusic commented on DragonSlayer.cpp
> +                attackItem.reset(nullptr);
The placement of this `attackItem->use` is inefficient, because you're checking every time this `while` loop runs. 

use the attack item BEFORE the `while()` loop is entered.
Your current code checks if the attackItem is nullptr before every call to `dragon->takeDamage`, which could potentially be lots of calls.
- [ ] revise

2021-08-26 04:27 UTC, cudabanger commented on DragonSlayer.cpp
> +                attackItem.reset(nullptr);
Spoken like someone who writes real-time audio processing code.

2021-08-26 17:44 UTC, matkatmusic approved these changes

2021-08-26 17:44 UTC, merged